### ISSUE TITLE
Missing data mentioned in documentation

### ISSUE THREAD

**Issue by joachimwolff** [rjdkmr/gcMapExplorer#2]
Hi,

you write in your documentation about data which is available in the folder `data` e.g. `data/HomerFormat/human_INL_sample1_matrix_1Mb_raw.txt`. Unfortunately, there is no such folder in your repository and I did not found a link to it. Can you a) point me to the location where this is available or b) upload these files?

Thanks a lot,

Joachim

**Comment by rjdkmr** [comment]
Hi,
Please find these files [here](https://drive.google.com/drive/folders/1t5Jphi33y_bgBs2FAae489ulgHOI3Rw6?usp=sharing).

Thank you very much for pointing out. Now this link is added in the website.

/Rajendra
