### ISSUE TITLE
rho_km2

### ISSUE THREAD

**Issue by LeilyR** [rjdkmr/gcMapExplorer#4]
May I ask what is the `rho_km2` parameter  in KR normalization and when it has been initialized for the first time?

**Comment by rjdkmr** [comment]
To know about the parameter, you have to read original publication (https://doi.org/10.1093/imanum/drs019). I have ported their MATLAB code to python line by line. You can see original ported code here with MATLAB code as comment: https://github.com/rjdkmr/gcMapExplorer/blob/master/gcMapExplorer/lib/normalizer.py#L49

If you want to see comparison with original KR MATLAB code: please look here: https://gcmapexplorer.readthedocs.io/en/latest/modules_examples/compare_KR_norm.html
